### ISSUE TITLE
Not showing monthCoverAttributes on scroll

### ISSUE THREAD

**Issue by IbrahimYildirim** [Glow-Inc/GLCalendarView#11]
I'am using GLCalendarView with **Xcode 7 and Swift 2**. Everything seems to be working fine, except the labels for the months that is supposed to show up when you scroll. 

I have set the monthCoverAttributes in the AppDelegate.

```
GLCalendarView.appearance().monthCoverAttributes = [NSFontAttributeName: UIFont(name: "Lato-Semibold", size: 19)!, NSForegroundColorAttributeName: UIColor.blackColor()]
```

(Doesn't work even when i don't set the monthCoverAttributes)

Anyone facing same issue? Am I doing something wrong?

**Comment by codingmoh** [comment]
Did you fix up the issue? I am basically running into the same trouble using ObjC Code as well.

**Comment by ltebean** [comment]
It works fine in the demo, can you debug the code to see what's wrong with it, it's in GLCalendarMonthCoverView line 47

**Comment by codingmoh** [comment]
It does not even fire....
when should it fire?

**Comment by codingmoh** [comment]
Okay, got it, you should have to fire calendarView.reload. So it gets displayed.

**Comment by ltebean** [comment]
Cool, then I will close this issue
