### ISSUE TITLE
Easier to select just one date range

### ISSUE THREAD

**Issue by bensebborn** [Glow-Inc/GLCalendarView#14]
I'd like the user to be able to select only one date range

I can do this by returning NO from:

```
- (BOOL)calenderView:(GLCalendarView *)calendarView canAddRangeWithBeginDate:(NSDate *)beginDate
  return NO;
```

   }

However, it's then quite difficult for the user to select a new range to replace the old without deleting.

What I'd ideally like to achieve, is when the user selects a date outside of the current range, the existing range is deleted, and a new range is started where they click.

Is that possible?

Thanks

**Comment by ltebean** [comment]
You could achieve it by:

```
- (BOOL)calenderView:(GLCalendarView *)calendarView canAddRangeWithBeginDate:(NSDate *)beginDate
{
    for (GLCalendarDateRange *range in calendarView.ranges) {
        [calendarView removeRange:range];
    }
    return YES;
}
```

**Comment by ltebean** [comment]
And you can find the demo here: https://github.com/Glow-Inc/GLCalendarView/tree/single-select
