### ISSUE TITLE
Binding returning nil

### ISSUE THREAD

**Issue by rick2ricks** [Glow-Inc/GLCalendarView#16]
Hi , i am having trouble while trying to bind a [String]  to a range.
it returns nil , is that a bug ? or am i missing something ?

thanks

**Comment by ltebean** [comment]
Because currently the DateRange instance holds a weak reference to the binding object.
The reason for making it a weak reference is:  usually we would load the model in the view controller, keep a strong reference to them, and the binding field is just for easy access to the model

**Comment by ltebean** [comment]
I will consider to make it a strong reference. But with the current version, you have to keep a strong reference to that [String]

**Comment by rick2ricks** [comment]
ohh i see, thank you. Nice calendar by the way.
