### ISSUE TITLE
Weird white lines?

### ISSUE THREAD

**Issue by Tj3n** [Glow-Inc/GLCalendarView#21]
It's only happened on iPhone 6s Plus, can someone give any idea why? It keep showing random white lines

Here's how it look:
<img width="466" alt="screen shot 2016-04-20 at 4 28 34 pm" src="https://cloud.githubusercontent.com/assets/13995715/14669993/6f2baeb2-0715-11e6-84d4-bb9614283a65.png">

**Comment by ltebean** [comment]
You need to change `[GLCalendarView appearance].padding` to ensure calendarViewWidth - 2 \* padding % 7 == 0
