### ISSUE TITLE
iPhone 6 Plus: White stripes on selected range

### ISSUE THREAD

**Issue by Hordaric** [Glow-Inc/GLCalendarView#7]
White stripes appear on selected range when running on iPhone 6 Plus. Please see attached screenshot.

<img width="467" alt="screen shot 2015-09-16 at 10 49 26 am" src="https://cloud.githubusercontent.com/assets/1645431/9899162/af09fa4e-5c60-11e5-89c8-7ed458704ca6.png">

**Comment by ltebean** [comment]
This is because `(screenWidth - padding * 2)  / 7` is not an integer. You can fix it by:

```
NSInteger screenWidth = [UIScreen mainScreen].bounds.size.width;
CGFloat paddingAll = screenWidth % 7 + 7;
[GLCalendarView appearance].padding = paddingAll / 2;
```
